[package]
name = "native-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
pollster = "0.3.0"
renderer = { path = "../../renderer" }
winit = "0.28.6"
